import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {menu,chooseCombination,templateOrder} from '../ui/dialogs.js';
import {shortcutIcon} from '../ui/icons.js';
test('context menu anchors to trigger; choice cancellation and template order are explicit',async()=>{
 const dom=new JSDOM('<button id="anchor">Site</button>');
 Object.assign(globalThis,{window:dom.window,document:dom.window.document,innerWidth:500,innerHeight:800,chrome:{runtime:{getURL:p=>'chrome-extension://test'+p}}});
 const proto=dom.window.HTMLDialogElement.prototype;
 proto.showModal=function(){this.open=true;};proto.close=function(){this.open=false;this.dispatchEvent(new dom.window.Event('close'));};
 proto.getBoundingClientRect=()=>({width:220,height:180});
 const anchor=document.getElementById('anchor');anchor.getBoundingClientRect=()=>({left:450,right:486,top:100,bottom:136});
 menu('Site',[['Авто',()=>{},{selected:true}],['Удалить',()=>{},{danger:true,icon:'trash'}]],anchor);
 let d=document.querySelector('dialog');assert.equal(d.style.left,'224px');assert.equal(d.style.top,'100px');assert.equal(d.querySelector('[aria-checked="true"]').textContent,'Авто');assert.equal(d.querySelector('button:last-child').textContent,'Удалить');d.close();
 let pending=chooseCombination();d=document.querySelector('dialog');assert.match(d.textContent,/Шаблон.*Группа/s);d.close();assert.equal(await pending,null,'Escape/cancel has no mutation result');
 const a={title:'A',url:'https://a.test'},b={title:'B',url:'https://b.test'};
 pending=templateOrder(a,b);d=document.querySelector('dialog');assert.equal(d.querySelectorAll('input').length,0,'no template name field');
 [...d.querySelectorAll('button')].find(x=>x.textContent==='Поменять местами').click();await Promise.resolve();await Promise.resolve();
 assert.match(d.querySelector('.site-row').textContent,/Сверху: B/);
 [...d.querySelectorAll('button')].find(x=>x.textContent==='Сохранить').click();assert.deepEqual(await pending,{reverse:true});
 const t=shortcutIcon({type:'template',top:a,bottom:b});assert.equal(t.querySelectorAll('.tile').length,2);assert.match(t.lastChild.textContent,/A/);
 const g=shortcutIcon({type:'group',title:'Group',color:'#ff0000'});assert.equal(g.style.color,'rgb(255, 0, 0)');assert.ok(g.querySelector('svg'));dom.window.close();
});
